image: gradle:jdk19-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - ./gradlew test

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script: echo "Define your deployment script!"
  environment: production