
image: gradle:jdk19-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  variables:
    HTTPS_PROXY: "https://localhost:5432"
    HTTP_PROXY: "https://localhost:5432"
    POSTGRES_DB: "sportsbook"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "exit"
    PGDATA: "/var/lib/postgresql/data"
    POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
  services:
  - name: postgres:11.7
    alias: db
    entrypoint: ["docker-entrypoint.sh"]
    command: ["postgres"]
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - ./gradlew test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
