
image: gradle:jdk19-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  variables:
    POSTGRES_DB: sportsbook
    POSTGRES_HOST: localhost
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: exit
  services:
  - name: postgres:14.3
    alias: db
    entrypoint: ["docker-entrypoint.sh"]
    command: ["postgres"]
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - ./gradlew test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
