image: gradle:jdk19-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  services:
  - postgres:14-alpine
  variables:
    POSTGRES_DB: sportbook
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "exit"
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - ./gradlew test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
